// Code generated by "enumer -type=Mailbox -trimprefix=Mailbox -json"; DO NOT EDIT.

package domain

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MailboxName = "UngültigInboxOutboxArchiveSent"

var _MailboxIndex = [...]uint8{0, 9, 14, 20, 27, 31}

const _MailboxLowerName = "ungültiginboxoutboxarchivesent"

func (i Mailbox) String() string {
	if i < 0 || i >= Mailbox(len(_MailboxIndex)-1) {
		return fmt.Sprintf("Mailbox(%d)", i)
	}
	return _MailboxName[_MailboxIndex[i]:_MailboxIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MailboxNoOp() {
	var x [1]struct{}
	_ = x[MailboxUngültig-(0)]
	_ = x[MailboxInbox-(1)]
	_ = x[MailboxOutbox-(2)]
	_ = x[MailboxArchive-(3)]
	_ = x[MailboxSent-(4)]
}

var _MailboxValues = []Mailbox{MailboxUngültig, MailboxInbox, MailboxOutbox, MailboxArchive, MailboxSent}

var _MailboxNameToValueMap = map[string]Mailbox{
	_MailboxName[0:9]:        MailboxUngültig,
	_MailboxLowerName[0:9]:   MailboxUngültig,
	_MailboxName[9:14]:       MailboxInbox,
	_MailboxLowerName[9:14]:  MailboxInbox,
	_MailboxName[14:20]:      MailboxOutbox,
	_MailboxLowerName[14:20]: MailboxOutbox,
	_MailboxName[20:27]:      MailboxArchive,
	_MailboxLowerName[20:27]: MailboxArchive,
	_MailboxName[27:31]:      MailboxSent,
	_MailboxLowerName[27:31]: MailboxSent,
}

var _MailboxNames = []string{
	_MailboxName[0:9],
	_MailboxName[9:14],
	_MailboxName[14:20],
	_MailboxName[20:27],
	_MailboxName[27:31],
}

// MailboxString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MailboxString(s string) (Mailbox, error) {
	if val, ok := _MailboxNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MailboxNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mailbox values", s)
}

// MailboxValues returns all values of the enum
func MailboxValues() []Mailbox {
	return _MailboxValues
}

// MailboxStrings returns a slice of all String values of the enum
func MailboxStrings() []string {
	strs := make([]string, len(_MailboxNames))
	copy(strs, _MailboxNames)
	return strs
}

// IsAMailbox returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mailbox) IsAMailbox() bool {
	for _, v := range _MailboxValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Mailbox
func (i Mailbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Mailbox
func (i *Mailbox) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Mailbox should be a string, got %s", data)
	}

	var err error
	*i, err = MailboxString(s)
	return err
}
